# ==============================================================================
# LuckyWheel - Java Minecraft Plugin
# Copyright (c) 2026 Daperkz
#
# plugin
# ==============================================================================

name: LuckyWheel
version: '${project.version}'
main: com.daperkz.luckywheel.LuckyWheelPlugin
api-version: 1.20
folia-supported: true
author: Daperkz
description: fully customizable lucky wheel plugin

permissions:
  Daperkz.luckywheel:
    description: Permission to use /luckywheel
    default: true
  Daperkz.luckywheel.admin:
    description: Permission to reload plugin and to give
    default: op

commands:
  luckywheel:
    description: "Main luckywheel command"
    permission: Daperkz.luckywheel
    permission-message: "<red>You do not have permission to use this command."
    usage: "/luckywheel <spin|give|reload> [arguments...]"
    aliases: [lw]
